# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bYRQtzEYO_pw8xmRzb_GyYLe79OcOnP
"""

#1(a)
str='Python is a case sensitive language'
print(len(str))

#1(b)
rev=str[::-1]
print(rev)

#1(c)
c=str[10:35]
print(c)

#1(d)
obj=str.replace('a case sensitive language','object oriented')
print(obj)

#1(e)
idx=str.index('a')
print(idx)

#1(f)
spc=str.replace(' ','')
print(spc)

#2
str='''Hey,{name} Here!
My SID is 2110{SID}
I am from {dep} department and my CGPA is {CGPA}'''
print(str.format(name='Rhythm Das',SID='9038',dep='Production and Industrial engineering',CGPA='8.0'))

#3(a)
a=56
b=10
g=a&b
h=bin(g)
i=h.replace('0b','')
print(i)

#3(b)
a=56
b=10
g=a|b
h=bin(g)
i=h.replace('0b','')
print(i)

#3(c)
a=56
b=10
g=a^b
h=bin(g)
i=h.replace('0b','')
print(i)

#3(d)
a=56
b=10
g=a<<2
h=bin(g)
i=h.replace('0b','')
print(i)

#3(e)
a=56
b=10
g=a>>2
h=bin(g)
j=a>>4
l=bin(j)
i=h.replace('0b','')
k=l.replace('0b','')
print(i,k)

#4
str=input("Enter the string:")
if 'name' in str:
  print("Yes")
else:
  print("No")

#5
a=int(input("Enter the length of the first side:"))
b=int(input("Enter the length of the second side:"))
c=int(input("Enter the length of the third side:"))
m=(a+b)>=c
n=(b+c)>=a
o=(a+c)>=b
d=int(m)
e=int(n)
f=int(o)
g=d+e+f
print({True:'Yes', False:'No'}[g==3])



#6
a=int(input("Enter the 1st number:"))
b=int(input("Enter the 2nd number:"))
n=a^b
count=0
while n:
 n=n&(n-1)
 count=count+1
print("Required number of bits to be flipped:",count)
